// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGcVloT5aisR-Md8r90wDLUrfbb07HIIg',
    appId: '1:704033933411:web:05adfc620c647e01a29056',
    messagingSenderId: '704033933411',
    projectId: 'resolv-5a7e2',
    authDomain: 'resolv-5a7e2.firebaseapp.com',
    storageBucket: 'resolv-5a7e2.firebasestorage.app',
    measurementId: 'G-1CBRLTM2QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFKhzkBL9uJRgFeyh449SCdWdb57B0yCI',
    appId: '1:704033933411:android:f279c11cfbdb1c3fa29056',
    messagingSenderId: '704033933411',
    projectId: 'resolv-5a7e2',
    storageBucket: 'resolv-5a7e2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGcVloT5aisR-Md8r90wDLUrfbb07HIIg',
    appId: '1:704033933411:web:4770f0154c3b4f96a29056',
    messagingSenderId: '704033933411',
    projectId: 'resolv-5a7e2',
    authDomain: 'resolv-5a7e2.firebaseapp.com',
    storageBucket: 'resolv-5a7e2.firebasestorage.app',
    measurementId: 'G-TVJE12ET4H',
  );
}
